name: 本番 CI/CD
on:
  push:
jobs:
  deploy:
    name: 接続検証
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 古いコンテナを落とします。
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pushd ${{ secrets.DISTPATH }}
            ls
            popd
            ls
